#!/usr/bin/env bash
#
# Publish the contents of site/ to the `production` branch.
#
# The production branch is a GENERATED DEPLOYMENT ARTIFACT. Its root is the
# deployable website (index.html, css/, js/, assets/ ...), never the repository
# layout. Nobody develops on it; every commit on it is produced by this script.
#
# Design notes
#   * Runs in a temporary git worktree, so the caller's checkout and current
#     branch are never touched.
#   * Bases the new commit on origin/production, so the push is a normal
#     fast-forward. No force-push, and deployment history is preserved.
#   * Wipes the worktree before copying, so files deleted from site/ are also
#     deleted from production rather than lingering forever.
#   * Copies ONLY site/. Repository tooling, notes, reports, the zip archives
#     and .github/ are outside site/ and therefore cannot leak into production.
#   * Validates before and after the copy, and only pushes once the tree is
#     known good, so a failure never leaves a half-published branch.
#
# Usage:  bash tools/publish-production.sh
# Env:    PRODUCTION_BRANCH (default: production)
#         SITE_DIR          (default: site)
#         DRY_RUN=1         build and verify the branch but do not push

set -euo pipefail

BRANCH="${PRODUCTION_BRANCH:-production}"
SITE_DIR="${SITE_DIR:-site}"
DRY_RUN="${DRY_RUN:-0}"

die() { printf '\n[publish-production] ERROR: %s\n' "$*" >&2; exit 1; }
log() { printf '[publish-production] %s\n' "$*"; }

command -v git >/dev/null 2>&1 || die "git is not available"
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "not inside a git repository"

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# ---------------------------------------------------------------- validation
[ -d "$SITE_DIR" ]                || die "source directory '$SITE_DIR' does not exist"
[ -f "$SITE_DIR/index.html" ]     || die "'$SITE_DIR/index.html' is missing - refusing to publish"
[ ! -e "$SITE_DIR/.git" ]         || die "'$SITE_DIR/.git' exists - refusing to publish a nested repository"

SOURCE_SHA="$(git rev-parse HEAD)"
SOURCE_SHORT="$(git rev-parse --short HEAD)"
SOURCE_REF="${SOURCE_REF:-$(git rev-parse --abbrev-ref HEAD)}"
log "source ref   : $SOURCE_REF"
log "source commit: $SOURCE_SHA"
log "publishing   : $SITE_DIR/ -> branch '$BRANCH'"

# identity (CI has none by default; leave a human's config alone if present)
git config user.name  >/dev/null 2>&1 || git config user.name  "zoneary-deploy[bot]"
git config user.email >/dev/null 2>&1 || git config user.email "deploy@zoneary.com"

# ----------------------------------------------------------------- worktree
TMP_PARENT="$(mktemp -d)"
WORKTREE="$TMP_PARENT/$BRANCH"
cleanup() {
  git worktree remove --force "$WORKTREE" >/dev/null 2>&1 || true
  rm -rf "$TMP_PARENT" >/dev/null 2>&1 || true
  git worktree prune >/dev/null 2>&1 || true
}
trap cleanup EXIT

log "fetching origin/$BRANCH (if it exists)"
git fetch --no-tags --quiet origin "+refs/heads/$BRANCH:refs/remotes/origin/$BRANCH" 2>/dev/null || true

if git rev-parse --verify --quiet "refs/remotes/origin/$BRANCH" >/dev/null; then
  log "existing branch found - building on top of it (history preserved)"
  git worktree add --quiet "$WORKTREE" -B "$BRANCH" "refs/remotes/origin/$BRANCH"
else
  log "branch does not exist yet - creating it from an empty root commit"
  EMPTY_TREE="$(git hash-object -t tree /dev/null)"
  ROOT_COMMIT="$(git commit-tree "$EMPTY_TREE" -m "Initialize $BRANCH deployment branch

Generated branch. Do not edit or develop here - see DEPLOYMENT.md on main.")"
  git branch -f "$BRANCH" "$ROOT_COMMIT"
  git worktree add --quiet "$WORKTREE" "$BRANCH"
fi

# --------------------------------------------------- replace tree completely
log "clearing previous deployment tree"
find "$WORKTREE" -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

log "copying $SITE_DIR/ into the branch root"
cp -a "$SITE_DIR/." "$WORKTREE/"

# defensive tidy-up of anything that should never be served
find "$WORKTREE" \( -name '.DS_Store' -o -name 'Thumbs.db' -o -name 'desktop.ini' \) -delete
[ ! -e "$WORKTREE/site" ]        || die "unexpected nested 'site/' at the branch root"
[ -f "$WORKTREE/index.html" ]    || die "index.html is not at the branch root after copy"

# ------------------------------------------------------------------- commit
cd "$WORKTREE"
git add -A

if git diff --cached --quiet; then
  log "production already matches $SOURCE_SHORT - nothing to publish"
  exit 0
fi

FILE_COUNT="$(git diff --cached --name-only | wc -l | tr -d ' ')"
log "staged changes: $FILE_COUNT file(s)"

git commit --quiet -m "Deploy site/ from $SOURCE_REF @ $SOURCE_SHORT

Generated by tools/publish-production.sh - do not edit this branch by hand.
The root of this branch is the deployable website; the development source
lives on main. See DEPLOYMENT.md on main.

Source commit: $SOURCE_SHA"

NEW_SHA="$(git rev-parse HEAD)"
log "production commit: $NEW_SHA"

# --------------------------------------------------------------------- push
if [ "$DRY_RUN" = "1" ]; then
  log "DRY_RUN=1 - branch built and verified locally, not pushed"
  log "root entries:"
  ls -A | sed 's/^/    /'
  exit 0
fi

log "pushing to origin/$BRANCH (fast-forward, no force)"
git push origin "$BRANCH"
log "done - production is now at $NEW_SHA"
